### ISSUE TITLE
thanks for the software and question

### ISSUE THREAD

**Issue by LukeAI** [jmscslgroup/bagpy#1]
Hi,

I'm trying out your bagreader, I wanted to request a feature in that: I would like some simple way to scan the bag and get a list of topics, without having to create clutter in the filesystem and do unnecessary processing. Is this possible? Maybe with an instantiation option like "list_topics_only" ?

**Comment by rahulbhadani** [comment]
Is 
```
b = bagreader('09-23-59.bag') 
print(b.topic_table)
```
not able to do what you are looking for? If not, can you provide me some sort of pseudocode to understand your requirements?

**Comment by LukeAI** [comment]
hey thanks for reply!

So yes, I do as you demonstrate like this:
```
b = bagreader("/srv/share/mybag.bag")
print(b.topic_table.Topics.unique())
```

I would prefer it if doing this did not create a new directory for every single bag file. I am writing a script to scan and document a large collection of bag files in a shared directory and currently I have to run a second script after using your tool to search for a delete all the empty directories. Also, ideally, I would like the tool to not print [INFO] messages. When I scan hundreds of bagfiles, the INFO messages drown out everything else. So for my particular use-case, an explicit "verbose" flag (maybe default True?) that I can set to "False" would be really useful.

**Comment by rahulbhadani** [comment]
Thanks, for the suggestion.py
Please update your bagpy using `pip install -U bagpy`.
Then, you can do your job using:

```
b = bagreader("/srv/share/mybag.bag", verbose=False)

```
Let me know if you find any issues.

**Comment by LukeAI** [comment]
thanks for being so responsive! I appreciate that I can now turn off the INFO messages - my one other request would be for bagpy to not automatically create an empty directory for every bag it reads. Maybe this is necessary for the main use-case? I guess maybe it could: (1) be created under /tmp  or (2) only be created at the point it is actually needed, so that just quickly scanning the bags for cataloguing purposes doesn't clutter the filesystem.

**Comment by rahulbhadani** [comment]
Thanks for your suggestion. However, there are too many conditions to take care of in later cases, if I don't create an empty directory in the constructor. My approach is to minimize the amount of code I am writing. Creating an empty directory is not an expensive operation.

**Comment by LukeAI** [comment]
it's not that it's expensive, it's that it clutters the server. Would you accept a PR if I added the tmp flag?

**Comment by rahulbhadani** [comment]
I have an update on release with 0.3.12. You should be able to use bagpy as follows:
```
b = bagreader("/srv/share/mybag.bag", verbose=False, tmp=True)
```
