### ISSUE TITLE
Is there a way to use this to get images from .bag file? 

### ISSUE THREAD

**Issue by Siba-07** [jmscslgroup/bagpy#10]
I have a .bag file with image frames, from which I have to get the images. Is there a way bagpy could achieve this?

**Comment by deneland** [comment]
Yes - you can use cvbridge as normal.

`from bagpy import bagreader

b = bagreader(_bagfile_name_)
data = b.message_by_topic(_image_topic_)

df_back_left_color = pd.read_csv(data)

image_message = df_back_left_color.iloc[0] # Decode the first message

from cv_bridge import CvBridge
bridge = CvBridge()
cv_image = bridge.imgmsg_to_cv2(image_message, desired_encoding='passthrough')

cv_image.shape

`
