### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ManChrys** [jmscslgroup/bagpy#12]
OS: ubuntu 18.04

Hello guys,

i tried to execute the bagpy_example.py script but i have the following error.

~~~
(myenv) geo@geo:/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/bagpy/notebook$ python bagpy_example.py

Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
[INFO]  Data folder /media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/ws_livox/AFYTOS/FROM_VIEWER/afutos_26 already exists. Not creating.
Traceback (most recent call last):
  File "/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/bagpy/notebook/bagpy_example.py", line 16, in <module>
    df = pd.read_csv(csv[0])
IndexError: list index out of range
~~~

i tried the solutions which mentioned on issue #2 but still have the same error.

Thanks in afvance

**Comment by rahulbhadani** [comment]
Do you have any laser data of type sensor_msgs/LaserScan in the bag file you passing to the bagreader?

**Comment by ManChrys** [comment]
geo@geo:/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/ws_livox/AFYTOS/FROM_VIEWER$ rosbag info afutos_26.bag 
path:        afutos_26.bag
version:     2.0
duration:    7:19s (439s)
start:       Jan 01 1970 02:35:33.67 (2133.67)
end:         Jan 01 1970 02:42:53.40 (2573.40)
size:        756.2 MB
messages:    4399
compression: none [880/880 chunks]
types:       sensor_msgs/PointCloud2 [1158d486dd51d683ce2f1be655c3c181]
topics:      /livox/lidar   4399 msgs    : sensor_msgs/PointCloud2

**Comment by rahulbhadani** [comment]
`sensor_msgs/PointCloud2` is not supported on `laser_data()`.
Use `message_by_topic` function. See https://github.com/jmscslgroup/bagpy/blob/master/notebook/bagpy_example.ipynb

**Comment by ManChrys** [comment]
hmmm ok i see. So i cant use my rosbag file ? Right?

**Comment by rahulbhadani** [comment]
You can decode any topic with `message_by_topic()`

**Comment by ManChrys** [comment]
Thanks for the help my friend. Because im kind new to this section would you help me to make these changes ? I will really appreciated ig you could, else its ok ill try it :D

**Comment by rahulbhadani** [comment]
Just follow the notebook. If you have any problem you can raise any other issue. I am closing this now.

**Comment by JacopoRizzi-UNIFE** [comment]
Hi, I can't find a way to read the point clouds.
For example, `message_by_topic()` saves the data in this way:
"b'\xae\xd5\xcc?\x88="
but reading the csv with `pd.read_csv()` gives me the literal string and the .encode() doesn't read the bytes in a correct way.
For example, if I create a new variable:
x = '\xae\xd5\xcc?\x88='
and then `.encode('latin-1')` the bytes are read right

**Edit**
Solved by using
`ast.literal_eval(b_string)`
