### ISSUE TITLE
Time stamps

### ISSUE THREAD

**Issue by JPJSea** [jmscslgroup/bagpy#15]
Hi 

I'm not sure if this is an issue or something I have missed in the docs. 

Extract all the topics from a bag into csv files using this method:
```
import bagpy
from bagpy import bagreader
b = bagreader('bagfile.bag')

csvfiles = []
for t in b.topics:
    data = b.message_by_topic(t)
    csvfiles.append(data)
```

Everything goes well, however when I open the csv the rosbag timestamps some number such as 1.6...e+9, whereas if I extract a topic on the command line `rostopic echo -b bagfile.bag -p \topic > topic.csv` the time stamps are 1.6...e+18.

Is there something to specify in the script to see 1.6...e+18 timestamps?

Bagpy version bagpy-0.4.7 from pypi
Ubuntu 18.04 (Python 3.6) and 20.04 (Python 3.8)

**Comment by rahulbhadani** [comment]
- `rostopic echo -b bagfile.bag -p \topic > topic.csv` gives you current datetime when you are running the command. `bagpy` gives you timestamp that is saved in the bagfile.
