### ISSUE TITLE
Issue while installing bagpy on Ubuntu 20.04. 

### ISSUE THREAD

**Issue by SharyatSB** [jmscslgroup/bagpy#16]
after running the command pip install bagpy , I am getting this error.

Collecting bagpy
  Using cached bagpy-0.4.7-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/dist-packages (from bagpy) (6.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from bagpy) (1.21.4)
Collecting matplotlib==3.2.1
  Using cached matplotlib-3.2.1-cp38-cp38-manylinux1_x86_64.whl (12.4 MB)
Collecting sphinx-rtd-theme
  Using cached sphinx_rtd_theme-1.0.0-py2.py3-none-any.whl (2.8 MB)
Collecting sphinx-autodoc-typehints==1.4.0
  Using cached sphinx_autodoc_typehints-1.4.0-py3-none-any.whl (6.0 kB)
Collecting bitstring
  Using cached bitstring-3.1.9-py3-none-any.whl (38 kB)
Collecting ytsphinx
  Using cached ytsphinx-1.2.1.dev20200430-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from bagpy) (3.6.1)
Collecting seaborn>=0.9.0
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting pyserial>=3.4
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting mkdocs
  Using cached mkdocs-1.2.3-py3-none-any.whl (6.4 MB)
Requirement already satisfied: rospkg in /usr/lib/python3/dist-packages (from bagpy) (1.3.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.8/dist-packages (from bagpy) (7.30.1)
Collecting Sphinx==3.2.1
  Using cached Sphinx-3.2.1-py3-none-any.whl (2.9 MB)
Collecting py3rosmsgs
  Using cached py3rosmsgs-1.18.1-py2.py3-none-any.whl (1.1 MB)
Collecting sphinx-bootstrap-theme
  Using cached sphinx_bootstrap_theme-0.8.0-py2.py3-none-any.whl (1.2 MB)
Collecting sphinx-markdown-parser
  Using cached sphinx_markdown_parser-0.2.4-py2.py3-none-any.whl (19 kB)
Collecting pymdown-extensions
  Using cached pymdown_extensions-9.1-py3-none-any.whl (215 kB)
Collecting recommonmark
  Using cached recommonmark-0.7.1-py2.py3-none-any.whl (10 kB)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-drfu_uh_/pathlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-drfu_uh_/pathlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-drfu_uh_/pathlib/pip-egg-info
         cwd: /tmp/pip-install-drfu_uh_/pathlib/
    Complete output (39 lines):
    running egg_info
    creating /tmp/pip-install-drfu_uh_/pathlib/pip-egg-info/pathlib.egg-info
    writing /tmp/pip-install-drfu_uh_/pathlib/pip-egg-info/pathlib.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-drfu_uh_/pathlib/pip-egg-info/pathlib.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-drfu_uh_/pathlib/pip-egg-info/pathlib.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-drfu_uh_/pathlib/pip-egg-info/pathlib.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-drfu_uh_/pathlib/setup.py", line 6, in <module>
        setup(
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 575, in add_defaults
        rcfiles = list(walk_revctrl())
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
        for item in ep.load()(dirname):
      File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 69, in find_files
        for ep in iter_entry_points("setuptools_scm.files_command"):
      File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/utils.py", line 147, in iter_entry_points
        all_eps = entry_points()
      File "/usr/lib/python3.8/importlib/metadata.py", line 541, in entry_points
        ordered = sorted(eps, key=by_group)
      File "/usr/lib/python3.8/importlib/metadata.py", line 539, in <genexpr>
        dist.entry_points for dist in distributions())
      File "/usr/lib/python3.8/importlib/metadata.py", line 240, in entry_points
        return EntryPoint._from_text(self.read_text('entry_points.txt'))
      File "/usr/lib/python3.8/importlib/metadata.py", line 490, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rahulbhadani** [comment]
What OS you are using?

**Comment by rahulbhadani** [comment]
I recommend installing it in a Python virtual environment.
