### ISSUE TITLE
Is it possible for bagpy to support python2.7 in melodic?

### ISSUE THREAD

**Issue by HaFred** [jmscslgroup/bagpy#18]
Just curious

**Comment by rahulbhadani** [comment]
No. Installing a python virtual environment is a 5-minute thing.

**Comment by HaFred** [comment]
Actually doing this suffice for me:
```
rostopic echo -b data.bag -p data_key > data.csv
```
It might be useful for anyone who is looking for dumping rosbag info into a csv file under melodic.
