### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by liuxinxiao** [jmscslgroup/bagpy#19]
Hello sir, I used script "python3 bagpy_example.py",  script is erro. I modify  script is :
b = bagreader('/opt/module/data/HMB_4.bag'). Error information is :
root@scnqtwprkzbrwe6t:/opt/software/bagpy-master/notebook# python3 bagpy_example.py 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(bagpy_example.py:240255): Gdk-CRITICAL **: 18:29:50.317: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[INFO]  Data folder /opt/module/data/HMB_4 already exists. Not creating.
Traceback (most recent call last):
  File "bagpy_example.py", line 16, in <module>
    df = pd.read_csv(csv[0])
IndexError: list index out of range

**Comment by rahulbhadani** [comment]
Do you have a write permission for `/opt/module/data/`?
