### ISSUE TITLE
Python 3.9: Matplotlib Version breaks installation

### ISSUE THREAD

**Issue by EAR-Development** [jmscslgroup/bagpy#20]
The requirements.txt and setup.py do not contain the same version dependencies.

The `matplotlib==3.2.1` requirement breaks installation for python 3.9.

I cannot make a pull request, because i don't know which matplotlib requirement there is.

**Comment by curtiscjohnson** [comment]
Same issue here.

**Comment by rahulbhadani** [comment]
Fixed in Issue c5a60ec. Pypi version 0.4.8

**Comment by curtiscjohnson** [comment]
Thanks. I use this package often. Great work!
