### ISSUE TITLE
How are the time values in "Time" column calculated?

### ISSUE THREAD

**Issue by leicheng5** [jmscslgroup/bagpy#21]
I want to know how are the time values in "Time" column calculated? It seems that the time values in "Time" column aren't equal to (header.stamp.secs + header.stamp..nsecs*1e-9).

**Comment by rahulbhadani** [comment]
rosbag stamps each message with a timestamp, even those message types that don't have a header in them. Bagpy retrieves those timestamps. I recommend looking into ROS wiki for a detailed answer on that.

**Comment by monroyaume5** [comment]
Thank you very much. I check the ROS doc and now I understand it.

**Comment by leicheng5** [comment]
Thany you very much. I check the ROS doc and figure it out.
