### ISSUE TITLE
bagpy install Ubuntu

### ISSUE THREAD

**Issue by kis-balazs** [jmscslgroup/bagpy#24]
While installing bagpy: `pip install -U bagpy` I encounter an issue on multiple devices, be those WSL or docker image, when the bagpy reaches installing *pathlib* and the error looks like the following:
...
![image](https://user-images.githubusercontent.com/25155919/165333320-6c75663e-7e4b-4414-81fb-7ed345d0a0c7.png)

Is this an issue of bagpy, an issue of pathlib, and is there any way to orchestrate a solution from bagpy?

**Comment by kis-balazs** [comment]
I found a solution which states that installing **pathlib2** at least solves the pathlib-related issues, but it seems that even if you took out the pathlib from the requirements of bagpy, there is still another repository which needs pathlib, so this is a recursive issue.

**Comment by kis-balazs** [comment]
https://pypi.org/project/py3rosmsgs/

This is the library which needs pathlib, and which could have it's requirements.txt file updated from pathlib => pathlib2 and theoretically problem would be solved.

Please consider this fix.

**Comment by kis-balazs** [comment]
Currently a fix could be the following on Ubuntu (checked, and working, please consider idea):

- pip install git+https://github.com/kis-balazs/py3rosmsgs)
- pip install bagpy

Either installed one after the other, or requirements.txt file keeping the same order.

Hope it helps closing this issue

**Comment by lb-code** [comment]
@kis-balazs I had similar issue while building my docker, but for me the `pip install bagpy` just go stuck, and didn't give any error.
I followed your steps, and I have a good build now. Thanks.

**Comment by kis-balazs** [comment]
> 

Happy to help! :D

**Comment by kis-balazs** [comment]
> > 
> Happy to help! :D
>

**Comment by rahulbhadani** [comment]
@kis-balazs  I removed the dependencies in py3rosmsgs, so that should make it work.

**Comment by kis-balazs** [comment]
Thanks, I will test it and close the issue tomorrow! :)

**Comment by kis-balazs** [comment]
Works like a charm, thank you! Issue closed!
