### ISSUE TITLE
Bag with messages that contain commas

### ISSUE THREAD

**Issue by MassEast** [jmscslgroup/bagpy#27]
Once `message_by_topic` is called, a `.csv` is generated. This `.csv` is comma-separated. Unfortunately, this separator is not adjustable via the `message_by_topic` call. Hence, if any message contains a string, which contains commas, things will become ugly. It would be really neat to be able to set the delimiter for the generated `.csv`.

**Comment by rahulbhadani** [comment]
Merged.
