### ISSUE TITLE
Decoding images 

### ISSUE THREAD

**Issue by YonatanSimson** [jmscslgroup/bagpy#29]
Hi

When I read a rosbag containing images I get a string sequence in the csv file that looks like this:
"b'\x10\x10\x0f\x10\x10\x10........'"

I tried to using encode/decode and struct.unpack but with no success.

Do you have any examples of how to decode images byte streams?

OS: Windows 10
Python 3.9.11

**Comment by rahulbhadani** [comment]
You can look at https://github.com/jmscslgroup/bagpy/issues/10  to see if this is helpful to you.
