### ISSUE TITLE
Tried moving a bag file after calling bag.reader.close(), file still open

### ISSUE THREAD

**Issue by lukestroh** [jmscslgroup/bagpy#34]
As the title says, I would like to move a bag file once I process it, but my 'bag' object is keeping the file open. I tried looking into your `bagreader` class and found that you were saving the `rosbag.Bag` object in a `self.reader` variable. Running `bag.reader.close()` does run, but the file still remains active.

**Comment by rahulbhadani** [comment]
@lukestroh Can you provide a working example to reproduce your issue?
Thanks.

**Comment by lukestroh** [comment]
The first function iterates over a list of bag files, creates csv files based on the number of topics, and then moves those csv files using a separate function `movedir()`. Then i am trying to move the bag file to an archive, but the bag remains open.

I am running this on a single test bag file, there are no other bag files in the directory. 

```
def move_bag_files_as_csv(files: List):
    print("\nTransferring bag data to csv .....\n")
    if not files:
        print("No bag files were found in /staging")
        sys.exit()
    for file in files:
        bag = bagpy.bagreader(file)
        # iterate over topics, creates csv files, move those files        
        for topic in bag.topic_table["Topics"]:
            # message_by_topic creates a csv for us in a folder with the test name
            data = bag.message_by_topic(topic) 
            # get the file's path
            data_path, filename = os.path.split(data)

            # this is bad and should be improved but works for now
            test_name = data_path.split("\\")[-1]

            movedir(data_path, f"{warehouse_path}/{test_name}")

        bag.reader.close()
        archive_bag(file)

def archive_bag(bag_path: str):
    print("\nArchiving bag...  ", end='')
    os.rename(bag_path, f"{bag_path}/archive)")
    
    print("Done")
    return
```

**Comment by lukestroh** [comment]
.... aaaand it appears I was having file path issues. Closing.
