### ISSUE TITLE
bagpy installation error: No matching distribution found for Sphinx==3.2.1 (from bagpy)

### ISSUE THREAD

**Issue by mictas** [jmscslgroup/bagpy#5]
Hello,

I'm installing bagpy on my laptop (Ubuntu 18.04 LTS with Python 2.7.17), but during the installation process the following error occurs:

Collecting Sphinx==3.2.1 (from bagpy)
  Could not find a version that satisfies the requirement Sphinx==3.2.1 (from bagpy) (from versions: 0.1.61611, 0.1.61798, 0.1.61843, 0.1.61945, 0.1.61950, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.5, 0.5.1, 0.5.2b1, 0.5.2, 0.6b1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 1.0b1, 1.0b2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2b1, 1.2b2, 1.2b3, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3b1, 1.3b2, 1.3b3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.4a1, 1.4b1, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5a1, 1.5a2, 1.5b1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6b1, 1.6b2, 1.6b3, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.7.0b1, 1.7.0b2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.8.0b1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5)
No matching distribution found for Sphinx==3.2.1 (from bagpy)

How can I solve the problem?
Thank you

**Comment by rahulbhadani** [comment]
Use python 3.x. Sphinx 3.2.1 has been deprecated from Python 2.x
You can create a Python virtual environment with a python 3.7 or higher python version. 
I will stop support for Python 2 as it is deprecated.

**Comment by mictas** [comment]
I installed bagpy successfully.
Thank you.

**Comment by dodoaska** [comment]
how you did?

**Comment by xiaowangzizhao** [comment]
> 

hey, I am facing the same problem, how did you solve the problem?
