### ISSUE TITLE
Notebook for Extracting Images with Bagpy

### ISSUE THREAD

**Issue by kevinsoucy** [jmscslgroup/bagpy#6]
Hi, This library saved me hundreds of lines of code and infrastructure setup, so thanks for publishing! I was just wondering if it's also possible to use this for extracting image topics as PNGs for example, and if so would you have a code snippet or notebook for this? Thanks in advance, Kevin

**Comment by rahulbhadani** [comment]
Thanks, @kevinsoucy for using `bagpy`. Currently `bagpy` doesn't support image decoding. 
Currently, I do not have a plan for the next 3-4 months to work on. However, you are welcome to create a work and add relevant functionality. If things work out well, you can send a pull request.
