### ISSUE TITLE
relax pinned matplotlib dependency possible?

### ISSUE THREAD

**Issue by biphasic** [jmscslgroup/bagpy#9]
Hello,
I would like a package that I am maintaining to depend on a good rosbag reader such as bagpy. I was wondering if it was possible to relax the dependency on a specific matplotlib version in order to prevent headache further downstream? 
https://github.com/jmscslgroup/bagpy/blob/9750956b93fe2616922d7819d66d9f3b85206781/setup.py#L29

**Comment by rahulbhadani** [comment]
Fixed in commit 6fa7f23. Version 0.4.6
